---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: jdk8
inputs:
- name: sagan-site-repo
outputs:
- name: build
caches:
- path: gradle
params:
  # JSPM github authentication is needed for the CI
  # otherwise install steps reach github API limitation
  JSPM_GITHUB_AUTH_TOKEN:
run:
  user: root
  path: /bin/bash
  args:
    - -ec
    - |
      ${PWD}/sagan-site-repo/concourse/scripts/build-sagan-site.sh